### ISSUE TITLE
[Enhancement] GitBook 网页super标签的可读性似乎不太好

### ISSUE THREAD

**Issue by FledgeXu** [TeamCovertDragon/Harbinger#1]
## Synopsis / 简介
[链接](https://harbinger.covertdragon.team/chapter-01/mcp.html)

![image](https://user-images.githubusercontent.com/16664654/54072098-014d5280-42b1-11e9-838c-3ab3b01b8dde.png)

## Analysis / 分析

因为中文字体字高的原因，和上行的行间距过小。
## Proposed Correction / 建议修改为……
```
    font-weight: bold;
    font-size: 14px;
```
![image](https://user-images.githubusercontent.com/16664654/54072136-5721fa80-42b1-11e9-8173-3ab737d6033f.png)

**Comment by Yesterday17** [comment]
这个问题我今天读的时候也发现了 @3TUSK 
或者改成[萌娘百科](https://zh.moegirl.org/%E4%BD%90%E4%BB%93%E7%BB%AB%E9%9F%B3)那样的纯黑 （:hover可见）也行<sup>不过好像不大好办</sup>

**Comment by FledgeXu** [comment]
这个好像需要自定义 GitBook 的模版才能解决了？

**Comment by SeraphJACK** [comment]
建议修改的效果和直接用strong效果相同

- Suggestion:
![TRKXP_}B`WAM19QK689)J4W](https://user-images.githubusercontent.com/25274081/54073351-277aee80-42c1-11e9-8592-7c6cd248203f.png)

- Strong:

![TWY`9A8$PZ_JZM YKKKFIVY](https://user-images.githubusercontent.com/25274081/54073358-32358380-42c1-11e9-90a6-e14a3728ed80.png)

**Comment by 3TUSK** [comment]
> 我早知道应该弄一个 Enhancement 的模板的，Erratum 是“勘误”的意思

> Edit: 我为什么又把 enchantment 和 enhancement 弄混了？

**Comment by 3TUSK** [comment]
![image](https://user-images.githubusercontent.com/9113033/54164014-48098c80-4418-11e9-88f2-c620eb519a52.png)
目前改成了这个样子。有更好的解决方案吗？

**Comment by FledgeXu** [comment]
我觉得还行。

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/54176011-f1f42200-44c7-11e9-9a47-29bbe4204f0b.png)
黑幕的效果的是这样的，如果感觉没问题我再合并（
