### ISSUE TITLE
[Erratum/Errata] IRecipeFactory 示例错误

### ISSUE THREAD

**Issue by luqin2007** [TeamCovertDragon/Harbinger#13]
## Synopsis / 简介

https://harbinger.covertdragon.team/chapter-21/forge-extension/recipe-factory.html
_factories.json 中，应使用 recipes 而非 factories

## Analysis / 分析

CraftingHelper.loadFactories 方法中注册 IRecipeFactory 的代码判断的是 recipes

```java
// forgeSrc-1.12.2-14.23.5.2838.jar net.minecraftforge.common.crafting.CraftingHelper
static void loadFactories(JsonObject json, JsonContext context)
    {
        // ingredients 略

        if (json.has("recipes"))
        {
            for (Entry<String, JsonElement> entry : JsonUtils.getJsonObject(json, "recipes").entrySet())
            {
                ResourceLocation key = new ResourceLocation(context.getModId(), entry.getKey());
                String clsName = JsonUtils.getString(entry.getValue(), "recipes[" + entry.getValue() + "]");
                register(key, getClassInstance(clsName, IRecipeFactory.class));
            }
        }

        // conditions 略
    }
```

## Proposed Correction / 建议修改为……
factories -> recipes

**Comment by Yesterday17** [comment]
确实。

https://github.com/TeamCovertDragon/MooncakeCraft/blob/1a321154f649dc7e75cd4879038524845b3bdc5b/src/main/resources/assets/mooncakecraft/recipes/_factories.json#L1-L5
```json
{
  "recipes": {
    "remain_bottle": "team.covertdragon.mooncakecraft.crafting.RemainBottleRecipeFactory"
  }
}
```

**Comment by SeraphJACK** [comment]
你不应该贴 [ForgeDoc](https://mcforge.readthedocs.io/en/latest/utilities/recipes/#factories) 么...

**Comment by Yesterday17** [comment]
> 你不应该贴 [ForgeDoc](https://mcforge.readthedocs.io/en/latest/utilities/recipes/#factories) 么...

之前我写的回忆一下……

**Comment by SeraphJACK** [comment]
~~我睡了，你们 merge 之后记得给 pr 和 issue 贴标签。(跑~~
