### ISSUE TITLE
[Erratum/Errata] 物品 metadata=MAX 时的特殊意义未提到

### ISSUE THREAD

**Issue by luqin2007** [TeamCovertDragon/Harbinger#18]
## Synopsis / 简介

4.2.1 Meta-hack 中，代码注释（Line:6）中提到

> // 最大值同时也有一个特殊含义，将在讲到合成表及 OreDictionary 时解释。

但 21.1.1 矿物词典中只字未提。

## Analysis / 分析

大概是漏写了。。。

## Proposed Correction / 建议修改为……

感觉像是指所有物品

**Comment by 3TUSK** [comment]
是的，~~漏写了，~~`OreDictionary.WILDCARD_VALUE` (`Short.MAX_VALUE`) 在矿物词典中代表“匹配所有 metadata 值（或者忽略损害值）”。
在矿物词典之外的行为是没有定义的。
