### ISSUE TITLE
[Erratum/Errata] Ingredient 的 isSimple 描述不准确

### ISSUE THREAD

**Issue by luqin2007** [TeamCovertDragon/Harbinger#20]
## Synopsis / 简介

21.1.3 1.1 实现Ingredient 节中，对 isSimple() 方法的描述有误或不准确
https://harbinger.covertdragon.team/chapter-21/forge-extension/ingredient-factory.html

## Analysis / 分析

我在尝试自定义一个 Ingredient 用以识别忽略damage的合成时，没有使用 RecipeItemHelper.pick 方法，带有damage值的物品无法正常参与合成。
查看了 ShapelessOreRecipe 类，发现 isSimple 方法影响 matches 中是否使用 RecipeItemHelper 进行判断（false使用 RecipeMatcher）。
同时，根据我的测试，当 isSimple() 返回 false 时，无序合成时仍可以调用 apply() 方法，无序合成也可以正常进行（我测试的合成表只有两个物品）。

我的MDK版本用的是 forge-1.12.2-14.23.5.2768

## Proposed Correction / 建议修改为……

希望能对 isSimple() 方法进行更详细的解释。毕竟，只看方法名的话。。。一个不简单的合成材料？

**Comment by liach** [comment]
isSimple是处理多种物品可以被同一个ingredient用的情况的，这种情况下强制使用二分图匹配。

**Comment by SeraphJACK** [comment]
`isSimple` 怎么说明，涉及到太多其他东西了... @3TUSK @liach

**Comment by liach** [comment]
isSimple 就是一个 ingredient 可以配对多种不同的物品，比如那个 3T 的例子里面第一个 ingredient 可以配对多种不同的木板，但是后面的只能配对一种木板。它并不会影响配方书功能，所以以前返回 true 的推荐不正确。

**Comment by luqin2007** [comment]
我的 isSimple 返回 false 也能匹配不同物品啊
因为我要同时匹配两个没有矿辞的物品，而且对耐久度范围也有要求，所以自定义了一个 DamageIngredient
```java
public DamageIngredient(Item[] items, int damageCount) {
    super(0);
    tools = NonNullList.create();
    for (Item item : items) {
        ItemStack itemStack = new ItemStack(item);
        tools.add(itemStack.copy());
        if (item.isDamageable() && damageCount > 0) {
            for (int i = 1; i < item.getMaxDamage(itemStack) - damageCount + 2; i++) {
                ItemStack stack = itemStack.copy();
                stack.setItemDamage(i);
                tools.add(stack);
            }
        }
    }
}

@Override
@Nonnull
public IntList getValidItemStacksPacked() {
    if (itemIds == null || lastSizeL != tools.size()) {
        itemIds = new IntArrayList(tools.size());
        for (ItemStack itemstack : tools) {
            int id = Item.REGISTRY.getIDForObject(itemstack.getItem()) << 16 | itemstack.getItemDamage() & 65535;
            itemIds.add(id);
        }
        lastSizeL = tools.size();
    }
    return itemIds;
}
```
这样写 传入的 item 数组都能使用的
感觉只提匹配多种物品有点不准确。返回true/false都能多匹配（OreIngredient返回了true）

**Comment by 3TUSK** [comment]
https://discordapp.com/channels/313125603924639766/437002009216942086/583466779842707466

> anything that isnt purely a single item and meta combination is not simple - Lex
