### ISSUE TITLE
[Erratum/Errata] 流体模型部分描述太过于简略

### ISSUE THREAD

**Issue by luqin2007** [TeamCovertDragon/Harbinger#21]
## Synopsis / 简介

27.4 流体渲染相关
https://harbinger.covertdragon.team/chapter-27/render.html

## Analysis / 分析

此处描述太过于简略，至少把 Flowing 和 Still 材质的w h比例要求说明白，以及mcmeta动画文件也该提一下
另外，Fluid 只接受一个 ResourceLocation 的构造是新版本 forge 有的吗？我在 2768 版本的 forge 中并没有找到

## Proposed Correction / 建议修改为……
。。。

**Comment by 3TUSK** [comment]
> 另外，Fluid 只接受一个 ResourceLocation 的构造是新版本 forge 有的吗？我在 2768 版本的 forge 中并没有找到

不，那是一个错误——根本没有只接受一个 `ResourceLocation` 的构造器，是我的失误。（这大概就是造轮子造多了的结果吧）

**Comment by 3TUSK** [comment]
@luiqn2007 写了一个初稿（见 PR #26），有时间的话烦请帮忙校读一下。

**Comment by luqin2007** [comment]
可以吧。。。我也不太了解，只知道静态纹理需要1：1，动态纹理要求我也不知道，mcmeta文件我也是看4z的文档才只要要的
另外，新版本forge好像有第三种纹理，可选，也不知道干啥的。。。叫啥忘了，我现在没在电脑前
