### ISSUE TITLE
[New Content Request]该抄哪些mod

### ISSUE THREAD

**Issue by exzhawk** [TeamCovertDragon/Harbinger#4]
## Synopsis / 简介

遇到教程没讲到的问题时, 可以去参考哪些mod的代码?

## Description / 详细信息

比如:
渲染物品建议看 mek
gui 建议看 botania
不建议看 reika 的 mod
建议看forestry

## Justification / 理由

虽然 Harbinger 收录的内容很广，但不可能覆盖所有内容，所以这里提供参考方向。

**Comment by Yesterday17** [comment]
你说我资瓷什么mod，我当然资瓷[林业](https://space.bilibili.com/5756570/channel/detail?cid=18472)啦！（逃

**Comment by 3TUSK** [comment]
> 绝了

八章附录目前正好都没有特殊安排。不过这样未免有夹杂私货的嫌疑……

**Comment by exzhawk** [comment]
写教程夹带私货是不可避免的，有好的私货可以拿来推广也没什么坏处
