### ISSUE TITLE
[New Content Request] 升级 Forge 版本到 14.23.5.2836

### ISSUE THREAD

**Issue by 3TUSK** [TeamCovertDragon/Harbinger#5]
## Synopsis / 简介

升级教程适用的 Forge 版本到 14.23.5.2821。

## Description / 详细信息

见上。

## Justification / 理由

构建 2821 中，`net.minecraftforge.common.util.Constants` 下新增了大量常量字段，涉及下列方法：

  - `World.setBlockState`/`World.notifyBlockUpdate`
  - `World.playEvent`
  - `EntityAIBase.setMutexBits`
  - `Entity.getFlag`
  - `AttributeModifier` 的构造器

有鉴于幻数的使用是 antipattern，有必要升级 Forge 版本以鼓励使用有具体名称的常量字段。编译器在编译常量表达式时也会优化掉对这些常量字段的引用，所以二进制兼容可以保证。

除此之外，目前使用的 14.23.5.2772 与 2821 相比，缺失了一些相对重要的新特性（`IRarity` 接口、一套耕地灌溉的小系统、`@Config.SlidingOption`等）与问题修复（`FluidStack.hashCode` 实现与 `FluidStack.equals` 不对应等），更新版本是唯一能使用这些新特性的方式。

综上，升级 Forge 势在必行。

## Remarks / 备注

N/A

**Comment by 3TUSK** [comment]
目标版本从 14.23.5.2821 改为 14.23.5.2836。

**Comment by liach** [comment]
怎么听上去这变成像1.7.10这种长期版本上写mod的教程了
