### ISSUE TITLE
[Erratum/Errata] 第三章图片无法显示

### ISSUE THREAD

**Issue by SeraphJACK** [TeamCovertDragon/Harbinger#6]
## Synopsis / 简介

第三章的图片无法加载。

## Analysis / 分析

discord cdn在国内无法访问

## Proposed Correction / 建议修改为……

更换新的图库/直接上传图片至仓库

**Comment by SeraphJACK** [comment]
~~这个锅让3T来背~~

**Comment by 3TUSK** [comment]
> First I need to confirm the copyright status of that pic...

**Comment by 3TUSK** [comment]
Status confirmed. We will host one copy inside this repo instead.
