### ISSUE TITLE
[Erratum/Errata] 第 4.2.5 章正文章节号错乱

### ISSUE THREAD

**Issue by TaoismDeepLake** [TeamCovertDragon/Harbinger#75]
## Synopsis / 简介

4.2.5 "关于实体的内容在第七章会详细解释"

## Analysis / 分析

此时实体是第八章了。第七章是“物理端，逻辑端……”

## Proposed Correction / 建议修改为……

"关于实体的内容在第八章会详细解释"

**Comment by 3TUSK** [comment]
> 这 bot 居然正常工作了！

**Comment by SeraphJACK** [comment]
只要不乱改标题这 bot 都能正常工作的(
